### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Teamrockit44** [ForgottenGlory/FGs-Modlists-Site#80]
Describe the issue that you're seeing.
Getting a unable to download Data_scripts.zip on masterstroke installation

**Comment by Teamrockit44** [comment]
![Uploading image.jpg…]()

**Comment by ForgottenGlory** [comment]
@Teamrockit44 What is your Discord username so I can help you

**Comment by Teamrockit44** [comment]
Shadow🐱👤#7915
